// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfMZjLZPxIQpnv7QIgA-Kxn4GuXjS9DmM',
    appId: '1:1068894781735:web:b65dc0ec2b6d72f9efe902',
    messagingSenderId: '1068894781735',
    projectId: 'messmanager-86242',
    authDomain: 'messmanager-86242.firebaseapp.com',
    storageBucket: 'messmanager-86242.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtbLAcWHQhaZxU5CAVmQ3DnDC2734LvRY',
    appId: '1:1068894781735:android:cb637bc028a849e8efe902',
    messagingSenderId: '1068894781735',
    projectId: 'messmanager-86242',
    storageBucket: 'messmanager-86242.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPoLquaRDmiGjDweq6LSthmAw-kMhWN0',
    appId: '1:1068894781735:ios:5d35eef5f229b9b3efe902',
    messagingSenderId: '1068894781735',
    projectId: 'messmanager-86242',
    storageBucket: 'messmanager-86242.firebasestorage.app',
    iosClientId: '1068894781735-hv0masgfq3lg3h70gf73abith88pkp75.apps.googleusercontent.com',
    iosBundleId: 'com.example.messManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBPoLquaRDmiGjDweq6LSthmAw-kMhWN0',
    appId: '1:1068894781735:ios:5d35eef5f229b9b3efe902',
    messagingSenderId: '1068894781735',
    projectId: 'messmanager-86242',
    storageBucket: 'messmanager-86242.firebasestorage.app',
    iosClientId: '1068894781735-hv0masgfq3lg3h70gf73abith88pkp75.apps.googleusercontent.com',
    iosBundleId: 'com.example.messManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfMZjLZPxIQpnv7QIgA-Kxn4GuXjS9DmM',
    appId: '1:1068894781735:web:c560d61d0835d1d5efe902',
    messagingSenderId: '1068894781735',
    projectId: 'messmanager-86242',
    authDomain: 'messmanager-86242.firebaseapp.com',
    storageBucket: 'messmanager-86242.firebasestorage.app',
  );
}
